Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.box = "mycentos7"
  config.vm.box_check_update = false
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 9200, host: 9200
  config.vm.network "forwarded_port", guest: 9300, host: 9300
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
end
